# Generated by Django 4.2.14 on 2024-07-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingCateories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_bidding', models.CharField(max_length=80, verbose_name='Формат аукциона')),
            ],
            options={
                'verbose_name': 'Формат Аукциона',
                'db_table': 'BiddingCategory',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, max_length=600, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lots_images', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Цена')),
                ('application_date', models.DateField(verbose_name='Заявки принимаются до:')),
                ('bidding_date', models.DateField(verbose_name='Дата проведения торгов')),
                ('url_etp', models.URLField(verbose_name='Ссылка на торги')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categories', verbose_name='Категория лота')),
                ('format_bidding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.biddingcateories', verbose_name='Формат проведения торгов')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
                'db_table': 'goods_lots',
            },
        ),
    ]
