# Generated by Django 4.2.14 on 2024-07-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_biddingcateories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='place',
            field=models.CharField(default='Уточняется', max_length=150, verbose_name='Местоположение'),
        ),
    ]
