# Generated by Django 4.2.18 on 2025-04-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_rename_biddingcateories_biddingcategories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категорий'},
        ),
        migrations.AlterModelOptions(
            name='lots',
            options={'ordering': ('id',), 'verbose_name': 'Лот', 'verbose_name_plural': 'Лоты'},
        ),
    ]
