# Generated by Django 4.2.18 on 2025-04-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_categories_options_alter_lots_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lots',
            table='lot',
        ),
    ]
