# Generated by Django 4.2.18 on 2025-04-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_lots_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lots',
            table='lots',
        ),
    ]
